name: dispatch workflow
on:
  workflow_dispatch
jobs:
  dispatch_workflow_job:
    runs-on: self-hosted
    steps:
      - name: msg
        run: echo "running dispatch_workflow_job on self hosted"
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: http://127.0.0.1:8101
          tlsSkipVerify: true
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/ci app_secret
      - name: Build Docker Image
        run: docker build . --file Dockerfile --build-arg app_secret="\${{ env.APP_SECRET }} -t vault-action-example-app-mac
