name: call workflow
on:
  # Manual trigger from the UI
  workflow_dispatch:
    inputs:
      message:
        description: 'call from ui'

  # Dependency to a forking workflow
  workflow_run:
    workflows: ["another workflow"]
    type:
      - complete
jobs:
  call_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: msg
        run: echo "running call_workflow_job"